import { DD_CHECKS } from './dd';
export const ACTOR_LABEL = { YOU: 'Team member', AGENT: 'AI assistant', ENGINE: 'System', ALL: 'Everyone' };
export const RULE_LABEL = { A: 'Single-fund limit', B: 'Equity strategy limit', C: 'Minimum cash reserve', D: 'Total allocation', E: 'Outdated NAV limit' };
export const STATUS_LABEL: Record<string,string> = {CURRENT:'Up to date',ATTENTION:'Needs review',OVERDUE:'Overdue',PASS:'Within limit',FAIL:'Needs attention',PENDING:'Awaiting evidence',BLOCKED:'Cannot proceed',CLOSED:'Received',EXCEPTION:'Needs review',MISSING:'Not received',NEW:'Screening','IN DD':'Due diligence',PARKED:'On hold'};
export const FIELD_LABEL: Record<string,string> = {'rule.E':'Outdated NAV limit','pack.sla':'Reporting deadline','nav.asOf':'NAV date','pack.ack':'NAV review','fee.adjustment.proposed':'Proposed fee adjustment','exposure.usd':'Allocation','verdict.state':'Review status','doc.status':'Document review','research.submission':'Research submission','research.decision':'Research decision',nav_usd:'Net asset value (USD)',as_of:'Valuation date',fund_id:'Fund',amount_usd:'Invoice amount (USD)',gl_code:'Expense classification',alloc_fund_id:'Fund allocation',fee_delta_usd:'Fee adjustment (USD)',fee_charged_pct:'Charged fee (%)',fee_expected_pct:'Expected fee (%)',restatement_pp:'NAV correction (percentage points)',annual_rate_pct:'Annual fee (%)',period_start:'Period start',period_end:'Period end'};
export const fieldLabel=(key:string)=>FIELD_LABEL[key] ?? key.split('_').join(' ').replace(/^./,c=>c.toUpperCase());
export function plainText(text:string):string {
  let value=text;
  for(const check of DD_CHECKS)value=value.split(check.id).join(check.name);
  for(const [key,label] of Object.entries(FIELD_LABEL))value=value.split(key).join(label);
  for(const [key,label] of Object.entries(RULE_LABEL))value=value.split(`Rule ${key}`).join(label);
  return value.split('SLA-02').join('Overdue NAV report').split('SLA').join('reporting deadline').split('ENGINE').join('System').split('AGENT').join('AI assistant').split('YOU').join('Team member').split('SOC-1').join('administrator controls report (SOC 1)').split('Rules A–E').join('portfolio limits').split('Book').join('Portfolio').split('IC gate').join('investment approval').split('IC signed').join('PM approved').split('stale-NAV cap').join('outdated NAV limit').split('staged').join('proposed').split('invariants').join('checks').split('Σ').join('Total').split('β').join('market sensitivity').split('FAILING').join('needs attention').split('FAIL').join('Needs attention').split('BLOCKED').join('Cannot proceed').split('CURRENT').join('Up to date').split('ATTENTION').join('Needs review').split('OVERDUE').join('Overdue').split('EXCEPTION').join('Needs review').split('CLOSED').join('Received').split('MISSING').join('Not received');
}
