import { useEffect, useState } from 'react';
import { useStore } from '../lib/store';
import { ddState, DD_CHECKS, chkFor, flagItems } from '../lib/dd';
import { daysSince, NAV_USD } from '../data/seed';
import { canReadWork } from '../lib/records';
import { STATUS_LABEL, plainText } from '../lib/language';
import { evaluate } from '../lib/screening';
import { Btn } from './Ui';
import { WorkCard } from './Team';
import DataLibrary from './DataLibrary';
import Monitoring from './Monitoring';
import Fees from './Fees';
import Activity from './Activity';
import type { FundTab } from '../lib/types';
const tabs: {id:FundTab;label:string}[]=[{id:'overview',label:'Overview'},{id:'work',label:'Research & diligence'},{id:'documents',label:'Documents & data'},{id:'operations',label:'Operations'},{id:'history',label:'Activity'}];
export default function FundPage(){
 const s=useStore();const [note,setNote]=useState('');
 useEffect(()=>setNote(''),[s.fundId]);
 const fund=s.funds.find(f=>f.id===s.fundId);const candidate=s.screener.find(f=>f.id===s.fundId);const name=fund?.name??candidate?.name;
 const assignments=s.assignments.filter(a=>a.fundId===s.fundId&&canReadWork(s.identity,a,s.docs));
 const active=assignments.filter(a=>a.status!=='Done');const review=active.find(a=>a.status==='Needs review');const next=review??active[0];
 const tab=s.fundTab==='verdicts'?'work':s.fundTab==='exposure'?'overview':s.fundTab;
 if(!name || !s.fundId)return <p className="p-6">Choose a fund from Funds.</p>;
 const id=s.fundId;const screening=candidate?evaluate(candidate.metrics,s.criteria):null;
 const status=fund?STATUS_LABEL[ddState(id).s]:STATUS_LABEL[candidate!.status];
 return <div className="flex h-full min-h-0 flex-col"><header className="shrink-0 border-b border-line bg-surface px-6 pt-4"><button onClick={()=>s.setView('funds')} className="text-xs text-ai">Funds / {fund?'Invested':'Candidates'}</button><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{name}</h1><p className="mt-1 text-sm text-muted">{fund?.strat??candidate?.tag} · {status}</p></div><span className="rounded border border-line px-3 py-1 text-xs">{fund?'Invested manager':candidate?.status==='IN DD'?'Due diligence':'Candidate screening'}</span></div><nav aria-label="Fund sections" className="mt-4 flex flex-wrap gap-1">{tabs.map(t=><button key={t.id} onClick={()=>{s.setFundTab(t.id);if(t.id!=='documents')s.openRecord('');}} className={`border-b-2 px-3 py-3 text-sm ${tab===t.id?'border-ai font-medium text-ai':'border-transparent text-muted hover:text-ink'}`}>{t.label}</button>)}</nav></header>
 <div className="min-h-0 flex-1 overflow-y-auto p-6">
 {tab==='overview'&&<div className="space-y-5"><section className="rounded-lg border border-ai/20 bg-ai/5 p-5"><h2 className="font-semibold">Next action</h2>{next?<><p className="mt-2 text-sm">{next.title}</p><p className="mt-1 text-xs text-muted">{review?'Reviewer':'Owner'}: {review?next.reviewer:next.owner} · Due {next.due} · {next.status}</p><p className="mt-2 text-sm text-muted">{next.blocker??next.next}</p><Btn className="mt-3" onClick={()=>s.openAssignment(next.id)}>{review?'Review submission':'Open assignment'}</Btn></>:<><p className="mt-2 text-sm">{candidate?'Review the screening evidence and decide what to investigate.':'No assigned follow-up is outstanding.'}</p><Btn className="mt-3" onClick={()=>candidate?s.startResearch(id):s.setFundTab('operations')}>{candidate?'Start research':'Review operations'}</Btn></>}</section>
 {fund&&<div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[['Current allocation',`$${((s.book[id]??fund.wt)/100*NAV_USD/1e6).toFixed(2)}M (${s.book[id]??fund.wt}%)`],['Year-to-date return',`${fund.ytd}%`],['Latest NAV date',fund.asOf??'Not available'],['Reporting status',STATUS_LABEL[fund.pack]??fund.pack]].map(([label,value])=><div key={label} className="rounded-lg border border-line bg-surface p-4"><p className="text-xs text-muted">{label}</p><b className="mt-2 block text-base">{value}</b></div>)}</div>}
 {fund&&<section className="rounded-lg border border-line bg-surface p-4"><h2 className="font-semibold">Issues to resolve</h2>{flagItems(id).length?flagItems(id).map(f=><div key={f.label} className="mt-3 border-t border-line pt-3"><b className="text-sm">{f.label}</b><p className="mt-1 text-sm text-muted">{plainText(f.body)}</p><button className="mt-2 text-xs text-ai" onClick={()=>s.setFundTab('operations')}>Review issue and follow-up →</button></div>):<p className="mt-2 text-sm text-muted">No outstanding issues in the current review.</p>}</section>}
 {screening&&<section className="rounded-lg border border-line bg-surface p-4"><h2 className="font-semibold">Screening summary · {screening.status}</h2><p className="mt-2 text-sm text-muted">{screening.checks.filter(c=>c.status==='Pass').length} checks pass; {screening.checks.filter(c=>c.status==='Fail').length} outside criteria; {screening.checks.filter(c=>c.status==='Needs evidence').length} need evidence.</p><button className="mt-3 text-sm text-ai" onClick={()=>s.setFundTab('work')}>Inspect evidence and research →</button></section>}
 <div className="flex gap-4 text-sm"><button className="text-ai" onClick={()=>s.setFundTab('documents')}>Open documents & approved data →</button>{fund&&<button className="text-ai" onClick={()=>s.setView('book')}>Review portfolio allocation →</button>}</div></div>}
 {tab==='work'&&<div className="space-y-6">{screening&&<section className="rounded-lg border border-line bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Screening evidence</h2><Btn onClick={()=>s.startResearch(id)}>Open research assignment</Btn></div><p className="my-3 text-xs text-muted">{candidate?.metricSource??'Evidence not supplied'} · {candidate?.metricAsOf??'Date unknown'}</p>{screening.checks.map(c=><div key={c.key} className="flex justify-between gap-3 border-t border-line py-2 text-sm"><span>{c.label}</span><span>{c.value??'Not supplied'} {c.value==null?'':c.unit} · {c.status}</span></div>)}<button className="mt-3 text-xs text-ai" onClick={()=>s.setView('funds')}>Compare candidates or edit screening criteria →</button></section>}
 <section><h2 className="mb-3 text-lg font-semibold">Research and follow-up</h2><p className="mb-4 text-sm text-muted">Analysts verify the evidence and add their judgment. The reviewer decides the next step.</p><div className="grid gap-3 lg:grid-cols-2">{assignments.map(a=><WorkCard key={a.id} assignment={a}/>)}</div>{!assignments.length&&<p className="text-sm text-muted">No research assignments yet.</p>}</section>
 {fund&&<section className="rounded-lg border border-line bg-surface p-4"><h2 className="mb-3 text-lg font-semibold">Diligence review</h2>{DD_CHECKS.map(c=>{const r=chkFor(id,c.id);return <details key={c.id} className="border-t border-line py-3"><summary className="flex cursor-pointer justify-between gap-3 text-sm"><span>{c.name}</span><span>{r.s==='PASS'?'Reviewed':r.s==='FAIL'?'Needs attention':'Awaiting evidence'}</span></summary><p className="mt-2 text-sm text-muted">{r.detail??r.obs}</p><details className="mt-2"><summary className="cursor-pointer text-xs text-muted">Technical reference</summary><code className="text-xs">{c.id}</code></details></details>})}<label className="mt-4 block text-sm">Review decision<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Summarize your assessment and any follow-up required." className="mt-2 block w-full rounded border border-line p-3"/></label><Btn className="mt-3" disabled={!note.trim()} onClick={()=>{s.fileVerdict(id,note);setNote('');}}>Record review decision</Btn>{s.ddVerdicts[id]&&<div className="mt-4 rounded bg-paper p-3 text-sm"><b>Last review: {s.ddVerdicts[id].signer}</b><p className="mt-1">{plainText(s.ddVerdicts[id].note)}</p><p className="mt-1 text-xs text-muted">{s.ddVerdicts[id].ts}</p></div>}</section>}</div>}
 {tab==='documents'&&<DataLibrary key={`${id}-${s.identity?.role}`} fundId={id}/>}
 {tab==='operations'&&<div className="space-y-8">{fund?<><div className="flex gap-2">{([['reporting','Reporting & monitoring'],['fees','Management fees']] as const).map(([key,label])=><button key={key} onClick={()=>s.setOperationsSection(key)} className={`rounded border px-4 py-2 text-sm ${s.operationsSection===key?'border-rail bg-rail text-white':'border-line bg-surface'}`}>{label}</button>)}</div>{s.operationsSection==='reporting'?<Monitoring fundId={id}/>:<Fees key={`${id}-${s.identity?.role}`} fundId={id}/>}</>:<section className="rounded border border-line bg-surface p-5"><h2 className="font-semibold">Before investment</h2><p className="mt-2 text-sm text-muted">Reporting monitoring and fee reconciliation begin once this fund is invested. Current diligence requests are in Research & diligence.</p><Btn className="mt-3" onClick={()=>s.setFundTab('work')}>Open diligence work</Btn></section>}</div>}
 {tab==='history'&&<Activity fundId={id}/>}
 </div></div>;
}
