import { useState } from 'react';
import { LogOut } from 'lucide-react';
import { useStore } from '../lib/store';
import { cn } from '../lib/cn';
export function Logo({size=22,onPaper=false}:{size?:number;onPaper?:boolean}) {return <svg width={size} height={size} viewBox="0 0 32 32" aria-hidden="true"><rect x="3" y="3" width="26" height="26" rx="2" fill="none" stroke={onPaper?'#1B2430':'#F6F3EC'}/><path d="M10 24 L16 8 L22 24 M12 18 H20" fill="none" stroke={onPaper?'#1B2430':'#F6F3EC'} strokeWidth="1.8"/></svg>;}
export default function Rail(){
 const s=useStore();const [settings,setSettings]=useState(false);const pipeline=s.screener.filter(c=>s.assignments.some(a=>a.fundId===c.id&&a.status!=='Done'));
 return <aside className="flex h-full w-[210px] shrink-0 flex-col bg-rail text-paper">
  <div className="flex items-center gap-2 px-4 py-5"><Logo/><b className="text-sm">APEX PACIFIC</b></div>
  <div data-tour="role.switch" className="mx-3 mb-6 flex items-center gap-2 rounded border border-white/15 px-2 py-2"><select aria-label="Workspace role" value={s.identity?.role} onChange={e=>s.login(e.target.value==='PM'?'a.chan@apexpacific.example':'l.wu@apexpacific.example')} className="min-w-0 flex-1 bg-rail text-xs"><option value="PM">A. Chan · PM</option><option value="Analyst">L. Wu · Analyst</option></select><button aria-label="Sign out" onClick={s.logout}><LogOut size={13}/></button></div>
  <nav aria-label="Main navigation" className="space-y-2 px-3">{([['today','Today','Work that needs attention'],['funds','Funds','Candidates and invested managers'],['book','Portfolio','Allocations and approvals']] as const).map(([key,label,description])=><button key={key} onClick={()=>s.setView(key)} className={cn('w-full rounded px-3 py-3 text-left',s.view===key || (key==='funds' && s.view==='fund')?'bg-white/10':'hover:bg-white/5')}><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-white/50">{description}</span></button>)}</nav>
  <div className="mt-6 min-h-0 flex-1 overflow-y-auto px-3"><p className="mb-2 px-3 text-xs text-white/40">Invested funds</p>{s.funds.map(f=><button key={f.id} onClick={()=>s.openFund(f.id)} className={cn('mb-1 w-full rounded px-3 py-2 text-left text-xs',s.view==='fund'&&s.fundId===f.id?'bg-white/10 text-white':'text-white/65 hover:text-white')}>{f.name}</button>)}{pipeline.length>0&&<><p className="mb-2 mt-4 px-3 text-xs text-white/40">Pipeline</p>{pipeline.map(c=><button key={c.id} onClick={()=>s.openFund(c.id)} className={cn('mb-1 w-full rounded px-3 py-2 text-left text-xs',s.view==='fund'&&s.fundId===c.id?'bg-white/10 text-white':'text-white/65 hover:text-white')}>{c.name}</button>)}</>}</div>
  <div className="space-y-3 border-t border-white/10 p-4 text-xs"><button onClick={()=>s.setAudit(true)} className="block text-white/65">All activity</button><button onClick={()=>setSettings(!settings)} className="block text-white/50">Presenter tools {settings?'▴':'▾'}</button>{settings&&<div className="space-y-3 rounded bg-white/5 p-3"><button className="block" onClick={()=>s.setModules(true)}>How this demo works</button><button className="block" onClick={()=>s.setShell(true)}>Agent console</button><button className="block" onClick={()=>useStore.getState().restartTour()}>Restart interactive tour</button><a className="block" href={import.meta.env.DEV?'/DEMO_V3_WALKTHROUGH.md':'https://github.com/Longhuiberkeley/apex-pacific-pms/blob/main/DEMO_V3_WALKTHROUGH.md'} target="_blank" rel="noreferrer">Presenter guide ↗</a><p className="text-white/45">Fictional demo · refresh resets work</p></div>}</div>
 </aside>;
}
