/** Browser regression suite. Start Vite and Chrome with --remote-debugging-port=9333 first. */
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const targets=await (await fetch('http://localhost:9333/json/list')).json();
const target=targets.find(t=>t.type==='page');
assert(target,'A Chrome page is required');
const ws=new WebSocket(target.webSocketDebuggerUrl);
await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
let seq=0;const pending=new Map();const errors=[];
ws.onmessage=event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Runtime.consoleAPICalled' && m.params.type==='error')errors.push(m.params.args.map(a=>a.value??a.description).join(' '));};
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description??r.exceptionDetails.text);return r.result.value;};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
try {
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1280,height:720,deviceScaleFactor:1,mobile:false});
 await call('Runtime.discardConsoleEntries');errors.length=0;
 await call('Page.navigate',{url:'http://localhost:5199/'});await wait(1200);
 const checks=await evaluate(`(async()=>{
 const {S,agent,evaluate,DEFAULT_CRITERIA,reconcileFee}=await import('/tests/browser-api.ts');
 const logs=[]; const check=(v,label)=>{if(!v)throw Error(label);logs.push(label);};
 window.demoStore=S;S.getState().login('a.chan@apexpacific.example');
 const metrics={return:11,volatility:14,drawdown:17,sharpe:1.1,history:42,notice:75,concentration:9,correlation:0.35};
 check(evaluate(metrics).status==='Eligible','Screen boundaries pass');check(evaluate({...metrics,correlation:undefined}).status==='Needs evidence','Missing evidence never passes');check(evaluate({...metrics,return:10,correlation:undefined}).checks.some(c=>c.status==='Fail'),'Failures retained with missing evidence');check(evaluate(metrics,DEFAULT_CRITERIA.map(c=>({...c,enabled:false}))).status==='No checks enabled','Disabled rules do not imply eligibility');
 const initial=S.getState().records.length;S.getState().editDocField('inv-pfs-q3','amount_usd','49000');check(S.getState().records.length===initial,'Draft edit does not save a record');S.getState().approveDoc('inv-pfs-q3');let record=S.getState().records.find(r=>r.docId==='inv-pfs-q3');check(record.values.amount_usd===49000 && typeof record.values.amount_usd==='number','Approval saves typed corrected values');S.getState().approveDoc('inv-pfs-q3');check(S.getState().records.length===initial+1,'Repeated approval does not duplicate records');S.getState().editDocField('inv-pfs-q3','amount_usd','1');check(S.getState().records.find(r=>r.docId==='inv-pfs-q3').values.amount_usd===49000,'Approved record remains read-only');
 S.getState().approveDoc('hal-nav-08');check(S.getState().halAck,'Approved NAV completes linked workflow');
 S.getState().rejectDoc('eml-mer-0807','Wrong document');check(!S.getState().records.some(r=>r.docId==='eml-mer-0807'),'Rejected draft creates no approved data');
 const fee={nav:17100000,annualRate:1.44,start:'2026-08-01',end:'2026-08-31',invoiced:22500};check(reconcileFee(fee).days===31,'Fee includes both dates');check(reconcileFee({...fee,start:'2026-02-30'}).ok===false,'Fee rejects impossible date');check(reconcileFee({...fee,start:'2026-09-01'}).ok===false,'Fee rejects reversed dates');check(reconcileFee({...fee,nav:NaN}).ok===false,'Fee rejects invalid number');check(reconcileFee({...fee,start:'2024-02-28',end:'2024-03-01'}).days===3,'Leap year uses actual days');check(!S.getState().approveFee(fee,'').ok,'Discrepancy requires explanation');check(S.getState().approveFee(fee,'Confirm corrected invoice with administrator.').ok,'PM can save explained reconciliation');
 const saved=S.getState().feeReviews.length;S.getState().approveFee(fee,'Confirm corrected invoice with administrator.');check(S.getState().feeReviews.length===saved,'Duplicate fee approval is idempotent');
 S.getState().runMonitoring();S.getState().runMonitoring();check(S.getState().assignments.filter(a=>a.id==='MON-SAB').length===1,'Repeated monitoring creates one investigation');
 S.getState().prepareResearch('MON-SAB');const draft=S.getState().assignments.find(a=>a.id==='MON-SAB').draft;check(S.getState().submitResearch('MON-SAB',draft,'form').ok,'Investigation can be submitted');check(S.getState().reviewResearch('MON-SAB','accepted','Obtain the outstanding administrator pack.').ok,'Human review creates follow-up');check(S.getState().funds.find(f=>f.id==='SAB').asOf==='2026-07-31','Research does not clear numerical breach');
 S.getState().login('l.wu@apexpacific.example');check(!agent('docs get private-reference').ok,'Analyst cannot read restricted original');check(!agent('records get DATA-terms-hal').ok,'Analyst cannot read restricted structured data');check(!agent('tasks get PM-REF').ok,'Analyst cannot read report with restricted source');check(!JSON.stringify(agent('funds get SIL')).includes('disciplined escalation'),'Fund aggregate omits restricted evidence');check(!S.getState().approveFee(fee,'Try approval').ok,'Analyst cannot approve PM reconciliation');check(!agent('book approve').ok,'Agent cannot approve investments');
 const added=agent('funds add',{name:'Test Meadow',metrics,metricSource:'Fictional live monthly series',metricAsOf:'2026-08-31'},'cli');check(added.ok,'CLI adds candidate: '+JSON.stringify(added));check(!agent('funds add',{name:'test meadow'},'cli').ok,'CLI rejects duplicate names');check(!agent('funds add',{name:'Invalid',metrics:{correlation:4}},'cli').ok,'CLI rejects out-of-range metrics');
 const taskId=added.data.assignmentId;const task=agent('tasks get '+taskId).data;check(task.fundId===added.data.id,'New candidate has a usable assignment');check(agent('tasks submit '+taskId,{recommendation:'Continue evidence gathering.',rationale:'Review the screening evidence and request independent records.',risks:'Missing operational evidence.',conditions:'Obtain independent administrator confirmation.',sources:task.sources.map(s=>s.id)},'cli').ok,'Agent submits report for new candidate');
 S.getState().login('a.chan@apexpacific.example');check(S.getState().reviewResearch(taskId,'changes requested','Clarify evidence quality.').ok,'Reviewer can request changes');const rev=S.getState().assignments.find(a=>a.id===taskId);check(rev.revisions.length===1 && rev.status==='In progress','Revision history retained');
 const committed=JSON.stringify(S.getState().book);S.getState().stage({...S.getState().book,NOR:90});S.getState().approveGate();check(JSON.stringify(S.getState().book)===committed,'Invalid allocation cannot be committed');S.getState().clearStage();S.getState().stage({...S.getState().book,SAB:5,CASH:17});S.getState().login('l.wu@apexpacific.example');S.getState().approveGate();check(JSON.stringify(S.getState().book)===committed,'Analyst cannot commit a valid allocation');S.getState().login('a.chan@apexpacific.example');S.getState().approveGate();check(S.getState().book.SAB===5,'PM can commit valid allocation');S.getState().setView('screening');return logs;
 })()`);
 for(const check of checks)console.log('PASS',check);
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('nav[aria-label="Main navigation"] button')].map(b=>b.querySelector('span').textContent)`),['Today','Funds','Portfolio'],'Three primary destinations');
 await evaluate(`window.demoStore.getState().openRecord('DATA-hal-nav-08')`);await wait(100);
 assert.deepEqual(await evaluate(`({view:window.demoStore.getState().view,fund:window.demoStore.getState().fundId,tab:window.demoStore.getState().fundTab})`),{view:'fund',fund:'HAL',tab:'documents'},'Approved NAV opens in its fund');
 assert(!(await evaluate('document.querySelector("main").innerText')).includes('Meridian_Statement'),'Fund documents omit unrelated funds');
 await evaluate(`window.demoStore.getState().openFund('NOR');window.demoStore.getState().setFundTab('work')`);await wait(100);
 assert((await evaluate('document.querySelector("main").innerText')).includes('Independent valuation controls'),'Diligence has descriptive names');
 assert(!/CHK-[0-9]+|SLA-02|pack[.]sla|ENGINE/.test(await evaluate('document.querySelector("main").innerText')),'Internal references are hidden by default');
 await evaluate(`window.demoStore.getState().openFund('SAB');window.demoStore.getState().setFundTab('history')`);await wait(100);
 assert(!/CHK-[0-9]+|SLA-02|pack[.]sla|ENGINE/.test(await evaluate('document.querySelector("main").innerText')),'Activity uses plain language');
 console.log('PASS main navigation, fund record routing, document isolation and language');
 await wait(200);
 for(const [width,height] of [[1280,720],[1920,1080]]){
  await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});
  for(const view of ['screening','library','monitoring','fees','team']){
   await evaluate(`window.demoStore.getState().setView('${view}')`);await wait(100);
   assert(await evaluate('document.querySelector("main").innerText.length>50'),`${view} renders`);
   if(view==='fees')assert((await evaluate('document.querySelector("main").innerText')).includes('Proposed reconciliation'),'Fee worksheet is reachable within fund operations');
   assert(await evaluate('document.documentElement.scrollWidth<=innerWidth'),`${view} no page overflow at ${width}`);
   const shot=await call('Page.captureScreenshot',{format:'png'});await writeFile(`/tmp/apex-${view}-${width}.png`,Buffer.from(shot.data,'base64'));
  }
 }
 await evaluate(`window.demoStore.getState().login('l.wu@apexpacific.example');window.demoStore.getState().setView('library')`);await wait(100);
 assert((await evaluate('document.body.innerText')).includes('Restricted document'),'Restricted placeholder is visible');
 assert(!(await evaluate('document.body.innerText')).includes('Manager reference note'),'Restricted title absent');
 // Exercise real HTTP command transport, with explicit browser session targeting.
 const session=await evaluate(`import('/tests/browser-api.ts').then(m=>m.agentSession)`);await wait(900);
 const command=await fetch('http://localhost:5199/api/demo/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session,command:'funds add',payload:{name:'Live Bridge Candidate'}})});
 const result=await command.json();assert(result.ok,result.message);assert(await evaluate(`window.demoStore.getState().screener.some(f=>f.id===${JSON.stringify(result.data.id)})`),'Bridge write appears in live browser');console.log('PASS HTTP bridge write updates browser');
 const before=await (await fetch('http://localhost:5199/raw/PacificFundServices_September_Invoice.pdf')).arrayBuffer();assert(Buffer.from(before).subarray(0,5).toString()==='%PDF-','Real PDF bytes');
 assert(Buffer.from(before).includes(Buffer.from('$48,750.00')),'Original PDF value remains unchanged after correction');
 // Click through the document flow from a fresh browser session.
 await call('Page.reload');await wait(1000);
 const click=async label=>{await evaluate(`(()=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(label)});if(!button)throw Error('Missing button: '+${JSON.stringify(label)});button.click();})()`);await wait(100);};
 await click('Skip MFA');await click('Document intake');
 await evaluate(`document.querySelectorAll('button').forEach(b=>{if(b.textContent.startsWith('PacificFundServices_September_Invoice.pdf'))b.click();})`);await wait(100);
 assert((await evaluate('document.body.innerText')).includes('Draft value'),'Document review labels draft values');
 await click('Original PDF');assert(await evaluate(`document.querySelector('iframe')?.title === 'PacificFundServices_September_Invoice.pdf'`),'Original PDF viewer opens');await click('Annotated review');
 await call('Emulation.setDeviceMetricsOverride',{width:1280,height:720,deviceScaleFactor:1,mobile:false});
 await evaluate(`document.querySelector('[data-field-input=gl_code]').scrollIntoView({block:'center'})`);await wait(100);
 const docShot=await call('Page.captureScreenshot',{format:'png'});await writeFile('/tmp/apex-document-review-1280.png',Buffer.from(docShot.data,'base64'));
 await evaluate(`(()=>{const input=document.querySelector('[data-field-input=gl_code]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'6200-Administration');input.dispatchEvent(new Event('input',{bubbles:true}));})()`);await wait(100);await click('Approve & save record');await click('View saved record');
 assert((await evaluate('document.body.innerText')).includes('6200-Administration'),'Corrected field visible in saved record');
 assert((await evaluate('document.body.innerText')).includes('read-only snapshot'),'Approval opens approved record destination');
 console.log('PASS document review buttons, real PDF viewer and saved-record navigation');
 assert.deepEqual(errors,[],'Browser console has no errors');console.log('PASS layouts, restricted placeholders, PDF asset and clean browser console');
 // ---- appended: login third option · interactive tour store slice · every CLI verb added this session ----
 const consoleLines=[];const priorMessage=ws.onmessage;ws.onmessage=e=>{priorMessage(e);const m=JSON.parse(e.data);if(m.method==='Runtime.consoleAPICalled')consoleLines.push(m.params.args.map(a=>a.value??a.description).join(' '));};
 await call('Page.reload');await wait(1500);
 assert(consoleLines.some(l=>l.includes('[parity] boot state OK — 5/6 packs · +6.7% · cash 11.0 · Sable 38d · badge 5 · Rule E BLOCKED')),'Boot parity line stays green on a fresh load');
 assert(!consoleLines.some(l=>l.includes('[parity] BROKEN')),'Boot parity never reports BROKEN');
 console.log('PASS dev boot parity console line');
 await evaluate(`(async()=>{const m=await import('/tests/browser-api.ts');window.demoStore=m.S;window.demoAgent=m.agent;window.demoSession=m.agentSession;return true})()`);
 const forbidden=/CHK-[0-9]+|SLA-02|pack[.]sla|ENGINE/;
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('button')].map(b=>b.textContent.trim())`),['Sign in','Skip MFA','Interactive demo'],'Login offers exactly three options with the interactive tour third');
 assert((await evaluate('document.body.innerText')).includes('Guided walkthrough · ~4 min · real screens'),'Third login option promises a guided walkthrough');
 await click('Interactive demo');await wait(200);
 assert.deepEqual(await evaluate(`({active:window.demoStore.getState().tourActive,chapter:window.demoStore.getState().tourChapter,step:window.demoStore.getState().tourStep,skipped:window.demoStore.getState().tourSkipped.join(),done:window.demoStore.getState().tourDone.join(),who:window.demoStore.getState().identity?.name+'/'+window.demoStore.getState().identity?.role})`),{active:true,chapter:null,step:0,skipped:'',done:'',who:'A. Chan/PM'},'Interactive demo signs in the PM and starts the tour');
 assert((await evaluate('document.body.innerText')).includes('Pick a chapter — any order'),'Tour opens on the chapter chooser');
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('button')].filter(b=>b.textContent.includes('steps ·')).map(b=>b.querySelector('b').textContent)`),['1 · The daily desk: documents on Today','2 · Screening: thresholds decide who gets an analyst','3 · Due diligence: Silk River, analyst → PM','4 · Add a fund candidate','5 · Portfolio and fees'],'Five tour chapters are on offer');
 assert((await evaluate('document.body.innerText')).includes('Start chapter 1'),'Chooser offers Start chapter 1');
 assert(!forbidden.test(await evaluate('document.querySelector("main").innerText')),'Tour chooser leaves main content free of internal codes');
 console.log('PASS login third option and tour chooser');
 const tourState=()=>evaluate(`(()=>{const s=window.demoStore.getState();return {active:s.tourActive,chapter:s.tourChapter,step:s.tourStep,skipped:s.tourSkipped.join(),done:s.tourDone.join()}})()`);
 await evaluate(`window.demoStore.getState().openTourChapter('desk')`);
 assert.deepEqual(await tourState(),{active:true,chapter:'desk',step:0,skipped:'',done:''},'openTourChapter opens a chapter at step 0');
 await evaluate(`window.demoStore.getState().tourNext()`);
 assert((await tourState()).step===1,'tourNext advances a step');
 await evaluate(`window.demoStore.getState().tourBack();window.demoStore.getState().tourBack()`);
 assert((await tourState()).step===0,'tourBack never rewinds before the first step');
 await evaluate(`window.demoStore.getState().tourNext(true)`);
 assert.deepEqual(await tourState(),{active:true,chapter:null,step:0,skipped:'',done:'desk'},'tourNext(done) records the chapter as done');
 await evaluate(`window.demoStore.getState().openTourChapter('screening');window.demoStore.getState().skipTourChapter()`);
 assert.deepEqual(await tourState(),{active:true,chapter:null,step:0,skipped:'screening',done:'desk'},'skipTourChapter records the skip and returns to the chooser');
 await evaluate(`window.demoStore.getState().openTourChapter('screening');window.demoStore.getState().tourNext(true)`);
 assert.deepEqual(await tourState(),{active:true,chapter:null,step:0,skipped:'',done:'desk,screening'},'Finishing a skipped chapter clears the skip');
 await evaluate(`window.demoStore.getState().exitTour()`);
 assert.deepEqual(await tourState(),{active:false,chapter:null,step:0,skipped:'',done:'desk,screening'},'exitTour keeps the record of done and skipped chapters');
 await evaluate(`window.demoStore.getState().restartTour()`);
 assert.deepEqual(await tourState(),{active:true,chapter:null,step:0,skipped:'',done:'desk,screening'},'restartTour reopens the chooser without wiping progress');
 await evaluate(`window.demoStore.getState().startTour()`);
 assert.deepEqual(await tourState(),{active:true,chapter:null,step:0,skipped:'',done:''},'startTour resets tour progress');
 await evaluate(`window.demoStore.getState().setFundsFilter('All')`);assert(await evaluate(`window.demoStore.getState().fundsFilter`)==='All','fundsFilter slice switches the Funds filter');
 await evaluate(`window.demoStore.getState().setFundsFilter('Candidates')`);
 console.log('PASS interactive tour store slice');
 const card=async title=>{await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.querySelector('b')&&x.querySelector('b').textContent.includes(${JSON.stringify(title)}));if(!b)throw Error('Missing chapter card: '+${JSON.stringify(title)});b.click();})()`);await wait(250);};
 const panel=async()=>evaluate(`(()=>{const p=[...document.querySelectorAll('div')].find(d=>typeof d.className==='string'&&d.className.includes('z-[110]'));return p?{text:p.innerText,raw:p.textContent}:null})()`);
 await card('The daily desk');
 let p=await panel();assert(p&&p.text.includes('Step 1 of 3'),'A chapter opens on its first step');
 assert(await evaluate(`!!document.querySelector('[data-tour="today.queue"]')`),'Desk step highlights the real Today queue');
 assert(!forbidden.test((await evaluate('document.querySelector("main").innerText'))+p.text),'Tour step copy and main content stay free of internal codes');
 await click('Next');assert((await panel()).text.includes('Step 2 of 3'),'Next advances the coach panel');
 await click('Back');assert((await panel()).text.includes('Step 1 of 3'),'Back rewinds the coach panel');
 await click('Skip chapter');await wait(150);
 assert((await evaluate('document.body.innerText')).includes('Skipped'),'Skip chapter marks the chapter skipped in the chooser');
 await click('Start chapter 1');await wait(150);
 assert((await panel())!==null,'Start chapter 1 opens the coach panel');
 await click('All chapters');await wait(150);
 assert((await panel())===null&&(await evaluate('document.body.innerText')).includes('Pick a chapter — any order'),'All chapters returns to the chooser');
 await card('Due diligence: Silk River');await wait(250);
 p=await panel();
 const det=await evaluate(`(()=>{const p=[...document.querySelectorAll('div')].find(d=>typeof d.className==='string'&&d.className.includes('z-[110]'));const d=p&&p.querySelector('details');return d?{open:d.open,summary:d.querySelector('summary')&&d.querySelector('summary').textContent,tech:d.textContent}:null})()`);
 assert(det&&det.open===false&&det.summary==='Technical details'&&det.tech.includes('carry-forward A-101-NEXT'),'Technical ids sit under a closed Technical details disclosure');
 assert(!p.text.includes('A-101')&&p.raw.includes('A-101'),'Technical ids are hidden from the readable tour copy');
 assert(await evaluate(`!!document.querySelector('[data-tour="assignment.submit"]')`),'Silk chapter opens the real assignment sheet');
 assert(!forbidden.test((await evaluate('document.querySelector("main").innerText'))+p.text),'Silk chapter copy and main content stay free of internal codes');
 await evaluate(`(()=>{const p=[...document.querySelectorAll('div')].find(d=>typeof d.className==='string'&&d.className.includes('z-[110]'));p.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));})()`);await wait(150);
 assert(await evaluate(`window.demoStore.getState().tourActive===false&&window.demoStore.getState().assignmentId===null`),'Escape exits the tour and closes its overlays');
 await click('Presenter tools ▾');await wait(100);await click('Restart interactive tour');await wait(200);
 assert(await evaluate(`window.demoStore.getState().tourActive===true`),'Restart interactive tour relaunches the tour');
 await card('Add a fund candidate');await wait(250);
 assert(await evaluate(`!!document.querySelector('[data-tour="intake.form"]')&&!!document.querySelector('[data-tour="screening.table"]')&&!!document.querySelector('[data-tour="screening.criteria"]')`),'Intake chapter targets the real screening surface');
 await click('Exit tour');await wait(150);
 assert(await evaluate(`window.demoStore.getState().tourActive===false`),'Exit tour leaves the tour');
 await evaluate(`window.demoStore.getState().restartTour();window.demoStore.getState().openTourChapter('book')`);await wait(250);
 assert(await evaluate(`window.demoStore.getState().view==='book'&&!!document.querySelector('[data-tour="book.table"]')`),'Portfolio chapter navigates to the real book table');
 await evaluate(`window.demoStore.getState().setShell(true);window.demoStore.getState().exitTour()`);
 assert(await evaluate(`window.demoStore.getState().shellOpen===true&&window.demoStore.getState().tourActive===false`),'exitTour leaves other panels open');
 await evaluate(`window.demoStore.getState().closeAllOverlays()`);
 console.log('PASS interactive tour walkthrough, highlight targets and language');
 const {execFile}=await import('node:child_process');const {fileURLToPath}=await import('node:url');
 const apexPath=fileURLToPath(new URL('apex.mjs',import.meta.url));
 const cliSession=await evaluate('window.demoSession');await wait(900);
 const run=(...a)=>new Promise(res=>execFile('node',[apexPath,...a,'--session='+cliSession],(e,stdout)=>res(stdout)));
 const cli=async(...a)=>JSON.parse(await run(...a));
 const usage=await run('help');
 for(const line of ['sessions','whoami','history','today queue','queue list','screening get','screening list','fees get HAL','monitoring get','dd get SAB','book get','book propose','book paste --raw','audit tail 10'])assert(usage.includes(`node scripts/apex.mjs ${line}`),`apex help advertises the CLI verb ${line}`);
 assert(usage.includes('Human levers')&&usage.includes('return BLOCKED with an audit entry'),'apex help states the human-lever fence');
 const sess=await cli('sessions');assert((sess.sessions??[]).some(x=>x.id===cliSession),'apex sessions lists the demo browser session');
 const hg=await evaluate(`window.demoAgent('help')`);
 assert(hg.ok&&Array.isArray(hg.data),'CLI help returns the grouped verb surface');
 assert.deepEqual(hg.data.map(g=>g.title),['CLI · external agent','In-app demo triggers','Human levers (UI; echoed as receipts; agents get BLOCKED + audit)'],'Help separates CLI verbs, demo triggers and human levers');
 const cliCmds=hg.data[0].verbs.map(v=>v.cmd);
 for(const cmd of ['help','whoami','history','today queue','queue list','screening list','screen list','fees get <FUND>','monitoring get [FUND]','dd get <FUND>','book paste --raw','book propose'])assert(cliCmds.includes(cmd),`Verb help lists the CLI verb ${cmd}`);
 assert(hg.data[1].verbs.map(v=>v.cmd).join()==='screen extract --now,screen add "<name>",agent demo','In-app demo triggers are grouped apart from CLI verbs');
 assert(hg.data[2].verbs.every(v=>v.gate==='HUMAN ONLY (UI lever — echoed here as a receipt)'),'Every human lever carries the HUMAN ONLY gate');
 const who=await cli('whoami');
 assert(who.ok&&who.data.actingAs==='external agent'&&who.data.via==='cli'&&who.data.signedIn.role==='PM','whoami reports the signed-in human behind the external agent');
 for(const g of ['tasks review','docs approve','docs reject','screen triage','dd verdict','book approve','today approve','fee approve','criteria apply'])assert(who.data.gated.includes(g),`whoami lists the gated lever ${g}`);
 const tq=await cli('today queue');
 assert(tq.ok&&tq.data.openApprovals===5,'today queue reports the 5 open approvals of boot state');
 assert.deepEqual(tq.data.pendingDocs.map(d=>d.id),['hal-nav-08','inv-pfs-q3','eml-mer-0807'],'today queue lists the pending documents');
 assert(tq.data.pendingDocs.every(d=>typeof d.quickEligible==='boolean')&&tq.data.triggers.sableAssessed===false&&tq.data.broker.parsed===false,'today queue reports quick-review eligibility, triggers and broker state');
 assert.deepEqual((await cli('queue list')).data,tq.data,'queue list is an alias for today queue');
 const sl=await cli('screening list');
 assert(sl.ok&&sl.data.pipeline.length===19&&sl.data.pipeline.some(x=>x.id==='SIL'&&x.score===null)&&sl.data.pipeline.some(x=>x.id==='C-001'&&x.score===null),'screening list dumps the full 19-row watchlist keeping null scores null');
 assert(sl.data.pipeline.every(x=>typeof x.status==='string'&&'metricSource' in x&&'metricAsOf' in x),'Watchlist rows carry their evidence fields');
 assert.deepEqual((await cli('screen list')).data,sl.data,'screen list is an alias for screening list');
 const sg=await cli('screening get');
 assert(sg.ok&&sg.data.results.every(r=>typeof r.status==='string'&&Array.isArray(r.checks)&&'metrics' in r&&'metricAsOf' in r),'screening get evaluates candidates with their evidence');
 const fg=await cli('fees get HAL');
 assert(fg.ok&&fg.data.ready===false&&fg.data.inputs===null&&fg.data.sources.length===3&&!fg.data.sources[0].present,'fees get HAL waits on the NAV record');
 const mg=await cli('monitoring get');
 assert(mg.ok&&mg.data.thresholdDays===30&&mg.data.checks.length===6,'monitoring get covers every fund');
 const sab=mg.data.checks.find(c=>c.fundId==='SAB');
 assert(sab.ageDays===38&&sab.result==='Breach'&&sab.investigation===null,'Sable NAV reads a 38d breach before any investigation');
 assert(mg.data.checks.filter(c=>c.result==='Pass').length===5,'The other five funds pass NAV freshness');
 assert((await cli('monitoring get SAB')).data.checks.length===1,'monitoring get filters to a single fund');
 const dg=await cli('dd get SAB');
 assert(dg.ok&&dg.data.state==='OVERDUE'&&dg.data.verdict===null,'dd get SAB reports the overdue diligence state');
 assert.deepEqual(dg.data.flags,['SLA-02','CHK-08'],'Diligence flags stay technical in the CLI');
 assert(dg.data.checks.length===10&&dg.data.checks[7].id==='CHK-08'&&dg.data.checks[7].name==='Independent valuation controls','dd get lists the named diligence checks');
 await evaluate(`window.demoStore.getState().approveDoc('hal-nav-08')`);await wait(150);
 const fr=await cli('fees get HAL');
 assert(fr.ok&&fr.data.ready===true&&fr.data.inputs.nav===17100000&&fr.data.inputs.annualRate===1.44&&fr.data.inputs.start==='2026-08-01'&&fr.data.inputs.end==='2026-08-31'&&fr.data.inputs.invoiced===22500,'fees get computes from the approved source records');
 assert(fr.data.computed.ok===true&&fr.data.computed.days===31&&typeof fr.data.computed.variance==='number'&&fr.data.reviews.length===0,'Fee comparison is code-computed over inclusive days');
 const paste=await cli('book paste --raw');
 assert(paste.ok&&/101[.]3/.test(paste.message),'book paste stages the seeded raw agent book: '+paste.message);
 assert.deepEqual(paste.data.violations.map(v=>v.rule).sort(),['A','C','D','E'],'The raw book trips the A/C/D/E rules');
 const bg=await cli('book get');
 assert(bg.data.committed.CASH===11&&bg.data.committed.NOR===22.5&&bg.data.proposed.CASH===7,'Staging never commits — the committed book is untouched');
 await writeFile('/tmp/apex-verify-book.json',JSON.stringify({NOR:22.5,KES:18,MER:15.5,HAL:12,SAB:11,KUR:10,CASH:11}));
 const bp=await cli('book propose','--json=/tmp/apex-verify-book.json');
 assert(bp.ok&&/committed book unchanged/.test(bp.message),'book propose stages book JSON without committing');
 const bare=await cli('book propose');
 assert(bare.ok===false&&/Provide book JSON/.test(bare.message),'book propose demands book JSON');
 const hist=await cli('history');
 assert(hist.ok&&hist.data.lines.some(l=>l.startsWith('» docs approve hal-nav-08')),'history lists form receipts alongside CLI runs');
 assert(hist.data.lines.some(l=>l.startsWith('» book paste --raw'))&&hist.data.lines.some(l=>l.startsWith('» book propose')),'history lists the new CLI receipts');
 const blocked=await evaluate(`(()=>{const levers=['ops parse monday.xls','ops reconcile monday.xls','ops ack HAL.restatement','ops queue-fx','ops escalate','ops open-pack','monitor assess SLA-02 --draft','today approve W-0001','today reject W-0001','docs approve hal-nav-08','docs reject hal-nav-08','docs edit inv-pfs-q3 amount_usd','tasks draft A-101 --example','tasks update A-101','tasks review A-101','book set NOR --usd=1','book stage --from=edit','book approve','book discard','policy intake MANUAL','screen triage SIL park','dd verdict SAB --state=current','fee approve HAL --review=FEE-9','criteria apply'];return levers.map(c=>{const r=window.demoAgent(c,undefined,'cli');const a=window.demoStore.getState().audit[window.demoStore.getState().audit.length-1];return [c,r.ok,a.action.startsWith('BLOCKED '+c)]})})()`);
 for(const [cmd,ok,gated] of blocked)assert(!ok&&gated,`Agent is BLOCKED with an audit receipt from: ${cmd}`);
 const unknown=await evaluate(`window.demoAgent('teleport ship')`);
 assert(unknown.ok===false&&unknown.message.includes('try help')&&unknown.message.includes('today queue'),'Unknown commands point back to help and the new verbs');
 assert.deepEqual(errors,[],'Tour and CLI flows keep the browser console clean');
 console.log('PASS CLI verb surface, receipts and the human-lever fence');
 assert((await cli('book propose --raw')).ok,'book propose --raw is an alias for book paste (AGENT_DEMO.md advertises the alias)');
 console.log('PASS book propose --raw alias');
 const nk=await cli('fees get KUR');assert(nk.ok&&nk.data.ready===false&&nk.data.inputs===null&&nk.data.reviews.length===0&&typeof nk.data.reason==='string','fees get explains a fund without fee records on file');
 const dh=await cli('dd get HAL');assert.deepEqual(dh.data.flags,['CHK-07'],'dd get reports each fund with its own open flags');assert(dh.data.state==='ATTENTION'&&dh.data.checks.length===10&&dh.data.checks.find(c=>c.id==='CHK-07').s==='FAIL'&&dh.data.checks.find(c=>c.id==='CHK-08').s==='PASS','dd get spreads per-fund check status over the shared ten checks');
 const mt=await cli('monitoring get KUR');assert(mt.ok&&mt.data.checks.length===1&&mt.data.checks[0].fundId==='KUR'&&mt.data.checks[0].result==='Pass','monitoring get filters to the named fund');
 console.log('PASS fees, diligence and monitoring reads across funds');
 const gateBefore=await evaluate('window.demoStore.getState().book.CASH');
 const denied=await cli('book approve');assert(denied.ok===false&&denied.message.includes('human'),'External CLI cannot approve a staged allocation');
 assert(await evaluate('window.demoStore.getState().book.CASH')===gateBefore,'External CLI approval attempt does not change the committed allocation');
 const trail=await cli('audit tail','1');assert(trail.ok&&trail.data.length===1&&trail.data[0].action.includes('BLOCKED book approve via cli'),'External CLI blocked decision appears in the audit trail');
 console.log('PASS external CLI human-decision fence and audit trail');
 await evaluate(`window.demoStore.getState().login('l.wu@apexpacific.example')`);await wait(150);
 const analyst=await cli('whoami');assert(analyst.ok&&analyst.data.signedIn.role==='Analyst','whoami follows live browser role changes');
 const restricted=await cli('fees get HAL');
 assert(restricted.ok&&restricted.data.ready===false&&restricted.data.restricted===true,'fees get HAL indicates restricted sources to analysts');
 assert(restricted.data.inputs===null&&restricted.data.computed===null,'fees get HAL does not disclose restricted terms or derived fee inputs to analysts: '+JSON.stringify(restricted.data));
 assert(restricted.data.sources.every(x=>x.access!=='PM'||x.present===false),'fees get marks restricted sources unavailable');
 console.log('PASS analyst fee data isolation across external CLI');
} finally { ws.close(); }
